import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

/**
 * Turns the SQL drizzle-kit wrote into a TypeScript module.
 *
 * The store applies migrations from an array held in the bundle, never from
 * files on disk: React Native has no filesystem to read them from. This script
 * is the bridge, and it runs at author time only.
 */

interface Journal {
  readonly entries: readonly { readonly tag: string }[];
}

const root = join(import.meta.dirname, '..');
const folder = join(root, 'migrations');
const target = join(root, 'src', 'plugins', 'store', 'migrations.ts');
const breakpoint = '--> statement-breakpoint';

const journal = JSON.parse(readFileSync(join(folder, 'meta', '_journal.json'), 'utf8')) as Journal;

const statementsOf = (tag: string): readonly string[] =>
  readFileSync(join(folder, `${tag}.sql`), 'utf8')
    .split(breakpoint)
    .map(statement => statement.trim())
    .filter(statement => statement.length > 0);

const quote = (statement: string): string => `    ${JSON.stringify(statement)},`;

const render = (tag: string): string =>
  [`  /* ${tag} */`, '  [', ...statementsOf(tag).map(quote), '  ],'].join('\n');

const body = [
  '/* Generated by `pnpm migrations`. Edit the schema and run it again. */',
  '',
  '/**',
  ' * Every migration, oldest first, each one a list of statements to run in',
  ' * order. The version a database has applied is its index plus one, held in',
  " * SQLite's own `user_version`, so the store needs no table of its own to know",
  ' * where it stands.',
  ' */',
  'const migrations: readonly (readonly string[])[] = [',
  ...journal.entries.map(entry => render(entry.tag)),
  '];',
  '',
  'export { migrations };',
  '',
].join('\n');

writeFileSync(target, body);
process.stdout.write(`${String(journal.entries.length)} migrations inlined into ${target}\n`);
