/**
 * The exact tRPC mutation paths the MCP catalog may publish.
 *
 * The catalog publishes NO mutation unless its exact path is listed here.
 * `DENYLISTED_TOP_LEVEL_SEGMENTS` (catalog.ts) still applies on top: a path
 * under `admin`, `debug` or `test` stays internal even when it appears below.
 * Every listed path needs a summary — hand-written in
 * `services/kilo-mcp/catalog.json` (the dump's keep-edit rule preserves it) or
 * generated by the dump's LLM pass.
 *
 * This file is the review surface for "what may an MCP client change": adding a
 * path is the decision, and the dump fails loudly when a listed procedure is
 * renamed or deleted instead of dropping it silently. The list starts with the
 * agent-profile authoring core because those mutations are user-scoped,
 * reversible and carry no billing or identity side effects.
 */
export const MCP_MUTATION_ALLOWLIST: readonly string[] = [
  // Agent-profile authoring core (agent-profiles-router.ts).
  'agentProfiles.create',
  'agentProfiles.update',
  'agentProfiles.delete',
  'agentProfiles.setAsDefault',
  'agentProfiles.clearDefault',
  'agentProfiles.setVar',
  'agentProfiles.deleteVar',
  'agentProfiles.setCommands',
  'agentProfiles.bindToRepo',
  'agentProfiles.unbindRepo',
];

/**
 * Whether a procedure path may be published as a mutation. Exact,
 * case-sensitive match against {@link MCP_MUTATION_ALLOWLIST}; there is no
 * prefix, glob or segment-level opt-in.
 */
export function isAllowedMutation(path: string): boolean {
  return MCP_MUTATION_ALLOWLIST.includes(path);
}
