import { integer, sqliteTable, text } from 'drizzle-orm/sqlite-core';

export const vercelSnapshotBuilds = sqliteTable('vercel_snapshot_builds', {
  organization_id: text('organization_id').primaryKey(),
  credential_id: text('credential_id').notNull(),
  build_generation: text('build_generation').notNull(),
  runtime_build_id: text('runtime_build_id').notNull(),
  step: text('step').notNull(),
  retry_count: integer('retry_count').notNull().default(0),
  next_attempt_at: integer('next_attempt_at'),
  builder_name: text('builder_name').notNull(),
  builder_operation_id: text('builder_operation_id').notNull(),
  builder_create_requested: integer('builder_create_requested').notNull().default(0),
  builder_session_id: text('builder_session_id'),
  validator_name: text('validator_name').notNull(),
  validator_operation_id: text('validator_operation_id').notNull(),
  validator_create_requested: integer('validator_create_requested').notNull().default(0),
  validator_session_id: text('validator_session_id'),
  validator_wrapper_requested: integer('validator_wrapper_requested').notNull().default(0),
  validator_wrapper_command_id: text('validator_wrapper_command_id'),
  validator_control_id: text('validator_control_id'),
  team_slug: text('team_slug'),
  project_slug: text('project_slug'),
  snapshot_baseline_json: text('snapshot_baseline_json'),
  snapshot_source_session_id: text('snapshot_source_session_id'),
  snapshot_id: text('snapshot_id'),
  snapshot_candidate_id: text('snapshot_candidate_id'),
  snapshot_requested: integer('snapshot_requested').notNull().default(0),
  last_error: text('last_error'),
  created_at: integer('created_at').notNull(),
  updated_at: integer('updated_at').notNull(),
});
