#!/bin/sh
set -eu

case "${1:-}" in
get) ;;
*) exit 0 ;;
esac

protocol=
host=
while IFS= read -r line || [ -n "$line" ]; do
	[ -z "$line" ] && break
	case "$line" in
	protocol=*) protocol="${line#protocol=}" ;;
	host=*) host="${line#host=}" ;;
	esac
done

[ "$protocol" = https ] || exit 0

username=
password=

case "$host" in
github.com)
	username=x-access-token
	password="${GH_TOKEN:-}"
	;;
bitbucket.org)
	username=x-token-auth
	password="${BITBUCKET_TOKEN:-}"
	;;
*)
	gitlab_host="${GITLAB_HOST:-gitlab.com}"
	gitlab_host="${gitlab_host#https://}"
	gitlab_host="${gitlab_host#http://}"
	gitlab_host="${gitlab_host%%/*}"
	if [ "$host" = "$gitlab_host" ]; then
		username=oauth2
		password="${GITLAB_TOKEN:-}"
	fi
	;;
esac

[ -n "$password" ] || exit 0

printf 'username=%s\npassword=%s\n' "$username" "$password"
