/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 44ce65a8c9edd090fa4ab4eff34210f3)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/wasteland.worker");
		durableNamespaces: "WastelandDO" | "WastelandContainerDO";
	}
	interface DevEnv {
		WASTELAND_AE: AnalyticsEngineDataset;
		WASTELAND_JWT_SECRET: SecretsStoreSecret;
		NEXTAUTH_SECRET: SecretsStoreSecret;
		ENVIRONMENT: "development";
		KILO_API_URL: "http://192.168.65.254:3000";
		WASTELAND_API_URL: "http://192.168.65.254:8787";
		WASTELAND: DurableObjectNamespace<import("./src/wasteland.worker").WastelandDO>;
		WASTELAND_CONTAINER: DurableObjectNamespace<import("./src/wasteland.worker").WastelandContainerDO>;
	}
	interface Env {
		WASTELAND_AE: AnalyticsEngineDataset;
		WASTELAND_JWT_SECRET: SecretsStoreSecret;
		NEXTAUTH_SECRET: SecretsStoreSecret;
		ENVIRONMENT: "development" | "production";
		KILO_API_URL: "http://192.168.65.254:3000" | "https://api.kilo.ai";
		WASTELAND_API_URL: "http://192.168.65.254:8787" | "https://wasteland.kiloapps.io";
		WASTELAND: DurableObjectNamespace<import("./src/wasteland.worker").WastelandDO>;
		WASTELAND_CONTAINER: DurableObjectNamespace<import("./src/wasteland.worker").WastelandContainerDO>;
		CF_VERSION_METADATA?: WorkerVersionMetadata;
		SENTRY_DSN?: string; // worker secret
		SENTRY_RELEASE?: string; // deploy-time --var
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT" | "KILO_API_URL" | "WASTELAND_API_URL">> {}
}
