/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false`
// then manually edited for wasteland-specific bindings.

declare namespace Cloudflare {
  interface Env {
    ENVIRONMENT: 'development' | 'production';
    KILO_API_URL: string;
    WASTELAND_API_URL: string;
    WASTELAND_CONTAINER: DurableObjectNamespace<
      import('./src/dos/WastelandContainer.do').WastelandContainerDO
    >;
    WASTELAND_ENCRYPTION_KEY: SecretsStoreSecret;
    NEXTAUTH_SECRET: SecretsStoreSecret;
    CF_VERSION_METADATA?: WorkerVersionMetadata;
  }
}
interface Env extends Cloudflare.Env {}
