CREATE TABLE `vercel_snapshot_builds` (
	`organization_id` text PRIMARY KEY NOT NULL,
	`credential_id` text NOT NULL,
	`build_generation` text NOT NULL,
	`runtime_build_id` text NOT NULL,
	`step` text NOT NULL,
	`retry_count` integer DEFAULT 0 NOT NULL,
	`next_attempt_at` integer,
	`builder_name` text NOT NULL,
	`builder_operation_id` text NOT NULL,
	`builder_create_requested` integer DEFAULT 0 NOT NULL,
	`builder_session_id` text,
	`validator_name` text NOT NULL,
	`validator_operation_id` text NOT NULL,
	`validator_create_requested` integer DEFAULT 0 NOT NULL,
	`validator_session_id` text,
	`validator_wrapper_requested` integer DEFAULT 0 NOT NULL,
	`validator_wrapper_command_id` text,
	`validator_control_id` text,
	`team_slug` text,
	`project_slug` text,
	`snapshot_baseline_json` text,
	`snapshot_source_session_id` text,
	`snapshot_id` text,
	`snapshot_candidate_id` text,
	`snapshot_requested` integer DEFAULT 0 NOT NULL,
	`last_error` text,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL
);
