/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-file /dev/null` (hash: dcb9e8ce2211e36cc622f7e8543f1246)
interface __BaseEnv_Env {
	HEADROOM_BEARER_TOKEN: SecretsStoreSecret;
	ENVIRONMENT: "production";
	HEADROOM_INSTANCE_COUNT: "2";
	HEADROOM_MODEL_ALLOWLIST: "kilo/poolside/laguna-m.1:free,kilo/stepfun/step-3.7-flash:free,kilo/anthropic/claude-opus-4.8,kilo/stealth/claude-opus-4.8,kilo/stealth/claude-opus-4.7,kilo/stealth/claude-sonnet-4.6,kilo/stealth/claude-opus-4.6,kilo/moonshotai/kimi-k2.7-code,kilo/anthropic/claude-sonnet-4.6,kilo/openai/gpt-5.5,kilo/google/gemini-3.1-pro-preview,kilo/minimax/minimax-m3,kilo/qwen/qwen3.7-plus,kilo/stealth/qwen3.6-plus,kilo/z-ai/glm-5.2";
	HEADROOM_MODEL_LIMITS: "{\"context_limits\":{\"kilo/poolside/laguna-m.1:free\":262144,\"kilo/stepfun/step-3.7-flash:free\":262144,\"kilo/anthropic/claude-opus-4.8\":1000000,\"kilo/stealth/claude-opus-4.8\":1000000,\"kilo/stealth/claude-opus-4.7\":1000000,\"kilo/stealth/claude-sonnet-4.6\":1000000,\"kilo/stealth/claude-opus-4.6\":1000000,\"kilo/moonshotai/kimi-k2.7-code\":262144,\"kilo/anthropic/claude-sonnet-4.6\":1000000,\"kilo/openai/gpt-5.5\":1050000,\"kilo/google/gemini-3.1-pro-preview\":1048576,\"kilo/minimax/minimax-m3\":1048576,\"kilo/qwen/qwen3.7-plus\":1000000,\"kilo/stealth/qwen3.6-plus\":1000000,\"kilo/z-ai/glm-5.2\":1048576}}";
	HEADROOM_MAX_BODY_BYTES: "1048576";
	HEADROOM_MAX_MESSAGES: "200";
	HEADROOM_MAX_CONTENT_CHARS: "750000";
	HEADROOM_MAX_TOKEN_BUDGET: "256000";
	HEADROOM_CONTAINER_REQUEST_TIMEOUT_MS: "25000";
	HEADROOM_STATELESS: "true";
	HEADROOM_TELEMETRY: "off";
	HEADROOM_SKIP_UPSTREAM_CHECK: "1";
	HEADROOM_NO_CCR_INJECT_TOOL: "1";
	HEADROOM_NO_CCR_MARKER: "1";
	HEADROOM_NO_CCR_PROACTIVE_EXPANSION: "1";
	HEADROOM_LOG_MESSAGES: "false";
	HEADROOM_RATE_LIMIT_ENABLED: "false";
	HEADROOM_LIMIT_CONCURRENCY: "8";
	HEADROOM_COMPRESS_WORKERS: "4";
	HEADROOM_KOMPRESS_MAX_CONCURRENT: "2";
	HEADROOM_TOOL_OUTPUT_COMPRESSION_PARALLELISM: "2";
	HEADROOM_CONTAINER: DurableObjectNamespace<import("./src/index").HeadroomContainer>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "HeadroomContainer";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT" | "HEADROOM_INSTANCE_COUNT" | "HEADROOM_MODEL_ALLOWLIST" | "HEADROOM_MODEL_LIMITS" | "HEADROOM_MAX_BODY_BYTES" | "HEADROOM_MAX_MESSAGES" | "HEADROOM_MAX_CONTENT_CHARS" | "HEADROOM_MAX_TOKEN_BUDGET" | "HEADROOM_CONTAINER_REQUEST_TIMEOUT_MS" | "HEADROOM_STATELESS" | "HEADROOM_TELEMETRY" | "HEADROOM_SKIP_UPSTREAM_CHECK" | "HEADROOM_NO_CCR_INJECT_TOOL" | "HEADROOM_NO_CCR_MARKER" | "HEADROOM_NO_CCR_PROACTIVE_EXPANSION" | "HEADROOM_LOG_MESSAGES" | "HEADROOM_RATE_LIMIT_ENABLED" | "HEADROOM_LIMIT_CONCURRENCY" | "HEADROOM_COMPRESS_WORKERS" | "HEADROOM_KOMPRESS_MAX_CONCURRENT" | "HEADROOM_TOOL_OUTPUT_COMPRESSION_PARALLELISM">> {}
}
