/* Generated by `pnpm migrations`. Edit the schema and run it again. */

/**
 * Every migration, oldest first, each one a list of statements to run in
 * order. The version a database has applied is its index plus one, held in
 * SQLite's own `user_version`, so the store needs no table of its own to know
 * where it stands.
 */
const migrations: readonly (readonly string[])[] = [
  /* 0000_blushing_vance_astro */
  [
    'CREATE TABLE `sessions` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`system` text NOT NULL,\n\t`model` text NOT NULL,\n\t`effort` text,\n\t`max_tokens` integer\n);',
    'CREATE TABLE `turns` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`session_id` text NOT NULL,\n\t`role` text NOT NULL,\n\t`content` text NOT NULL,\n\tFOREIGN KEY (`session_id`) REFERENCES `sessions`(`id`) ON UPDATE no action ON DELETE no action\n);',
    'CREATE INDEX `turns_session_id_id` ON `turns` (`session_id`,`id`);',
  ],
  /* 0001_tranquil_reptil */
  [
    'CREATE TABLE `parts` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`turn_id` text NOT NULL,\n\t`session_id` text NOT NULL,\n\t`kind` text NOT NULL,\n\t`body` text NOT NULL,\n\t`media` text,\n\tFOREIGN KEY (`turn_id`) REFERENCES `turns`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`session_id`) REFERENCES `sessions`(`id`) ON UPDATE no action ON DELETE no action\n);',
    'CREATE INDEX `parts_session_id_id` ON `parts` (`session_id`,`id`);',
    'ALTER TABLE `turns` DROP COLUMN `content`;',
  ],
  /* 0002_bent_susan_delgado */
  ['ALTER TABLE `parts` ADD `signature` text;'],
  /* 0003_flaky_gideon */
  ['ALTER TABLE `sessions` ADD `prompted` integer;'],
];

export { migrations };
