/* eslint-disable */
// Generated by Wrangler by running `wrangler types` (hash: 94f56b10f188d507133e5a565a91884c)
// Runtime types generated with workerd@1.20260302.0 2026-01-27 nodejs_compat
// Note: runtime types are loaded via reference directive below to avoid conflicts
// with @cloudflare/workers-types loaded by transitive type dependencies (e.g. @sentry/cloudflare).
/// <reference types="@cloudflare/workers-types" />
type GetTokenForRepoSuccess = {
	success: true;
	token: string;
	installationId: string;
	accountLogin: string;
	appType: 'standard' | 'lite';
};
type GetTokenForRepoFailure = {
	success: false;
	reason: 'database_not_configured' | 'invalid_repo_format' | 'no_installation_found' | 'invalid_org_id';
};
type GetTokenForRepoResult = GetTokenForRepoSuccess | GetTokenForRepoFailure;
type GitTokenService = {
	getTokenForRepo(params: { githubRepo: string; userId: string; orgId?: string }): Promise<GetTokenForRepoResult>;
	getToken(installationId: string, appType?: 'standard' | 'lite'): Promise<string>;
};
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/gastown.worker");
		durableNamespaces: "GastownUserDO" | "AgentIdentityDO" | "TownContainerDO" | "TownDO" | "AgentDO";
	}
	interface DevEnv {
		GIT_TOKEN_SERVICE?: GitTokenService;
		GASTOWN_JWT_SECRET: SecretsStoreSecret;
		ENVIRONMENT: "development";
		CF_ACCESS_TEAM: "engineering-e11";
		CF_ACCESS_AUD: "7f6eda4c0714f6ea2afb74a3f055db65659b67571a913eab42468636a9b8c8be";
		KILO_API_URL: "http://192.168.65.254:3000";
		GASTOWN_API_URL: "http://192.168.65.254:8787";
		GASTOWN_USER: DurableObjectNamespace<import("./src/gastown.worker").GastownUserDO>;
		AGENT_IDENTITY: DurableObjectNamespace<import("./src/gastown.worker").AgentIdentityDO>;
		TOWN: DurableObjectNamespace<import("./src/gastown.worker").TownDO>;
		TOWN_CONTAINER: DurableObjectNamespace<import("./src/gastown.worker").TownContainerDO>;
		AGENT: DurableObjectNamespace<import("./src/gastown.worker").AgentDO>;
		GASTOWN_AE?: AnalyticsEngineDataset;
	}
	interface Env {
		GIT_TOKEN_SERVICE?: GitTokenService;
		GASTOWN_JWT_SECRET: SecretsStoreSecret;
		ENVIRONMENT: "development" | "production";
		CF_ACCESS_TEAM: "engineering-e11";
		CF_ACCESS_AUD: "7f6eda4c0714f6ea2afb74a3f055db65659b67571a913eab42468636a9b8c8be";
		KILO_API_URL: "http://192.168.65.254:3000" | "https://api.kilo.ai";
		GASTOWN_API_URL: "http://192.168.65.254:8787" | "https://gastown.kiloapps.io";
		GASTOWN_USER: DurableObjectNamespace<import("./src/gastown.worker").GastownUserDO>;
		AGENT_IDENTITY: DurableObjectNamespace<import("./src/gastown.worker").AgentIdentityDO>;
		TOWN: DurableObjectNamespace<import("./src/gastown.worker").TownDO>;
		TOWN_CONTAINER: DurableObjectNamespace<import("./src/gastown.worker").TownContainerDO>;
		AGENT: DurableObjectNamespace<import("./src/gastown.worker").AgentDO>;
		HYPERDRIVE?: Hyperdrive;
		NEXTAUTH_SECRET?: SecretsStoreSecret;
		GASTOWN_AE?: AnalyticsEngineDataset;
		SENTRY_DSN?: string;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT" | "CF_ACCESS_TEAM" | "CF_ACCESS_AUD" | "KILO_API_URL" | "GASTOWN_API_URL">> {}
}
