/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 5a54445493a1c6efa93aadfac11e9410)
interface __BaseEnv_Env {
	WEBHOOK_TOKEN_CACHE: KVNamespace;
	HYPERDRIVE: Hyperdrive;
	WEBHOOK_DELIVERY_QUEUE: Queue;
	INTERNAL_API_SECRET: SecretsStoreSecret | string;
	CALLBACK_TOKEN_SECRET: SecretsStoreSecret | string;
	NEXTAUTH_SECRET: SecretsStoreSecret | string;
	CF_VERSION_METADATA: WorkerVersionMetadata;
	ENVIRONMENT: "development" | "production";
	KILOCODE_BACKEND_BASE_URL: "http://localhost:3000" | "https://api.kilo.ai";
	KILOCLAW_API_URL: "http://localhost:8795" | "https://claw.kilosessions.ai";
	SHARED_RESOURCE_TOKENS_ENABLED: "false";
	WEBHOOK_AGENT_URL: string;
	TRIGGER_DO: DurableObjectNamespace<import("./src/index").TriggerDO>;
	CLOUD_AGENT: Fetcher /* cloud-agent-next-dev */ | Fetcher /* cloud-agent-next */;
	KILO_CHAT: Service /* entrypoint KiloChatService from kilo-chat */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "TriggerDO";
	}
	interface DevEnv {
		WEBHOOK_TOKEN_CACHE: KVNamespace;
		HYPERDRIVE: Hyperdrive;
		WEBHOOK_DELIVERY_QUEUE: Queue;
		INTERNAL_API_SECRET: SecretsStoreSecret;
		CALLBACK_TOKEN_SECRET: SecretsStoreSecret;
		NEXTAUTH_SECRET: SecretsStoreSecret;
		CF_VERSION_METADATA: WorkerVersionMetadata;
		ENVIRONMENT: "development";
		KILOCODE_BACKEND_BASE_URL: "http://localhost:3000";
		KILOCLAW_API_URL: "http://localhost:8795";
		SHARED_RESOURCE_TOKENS_ENABLED: "false";
		NEXTAUTH_SECRET: string;
		INTERNAL_API_SECRET: string;
		CALLBACK_TOKEN_SECRET: string;
		WEBHOOK_AGENT_URL: string;
		TRIGGER_DO: DurableObjectNamespace<import("./src/index").TriggerDO>;
		CLOUD_AGENT: Fetcher /* cloud-agent-next-dev */;
		KILO_CHAT: Service /* entrypoint KiloChatService from kilo-chat */;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT" | "KILOCODE_BACKEND_BASE_URL" | "KILOCLAW_API_URL" | "SHARED_RESOURCE_TOKENS_ENABLED" | "NEXTAUTH_SECRET" | "INTERNAL_API_SECRET" | "CALLBACK_TOKEN_SECRET" | "WEBHOOK_AGENT_URL">> {}
}
declare module "*.sql" {
	const value: string;
	export default value;
	}