/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 97065f3567b7a9e2884b8ff7f63a6a29)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env {
		AUTO_ROUTING_CONFIG: KVNamespace;
		AUTO_ROUTING_CLASSIFIER_METRICS: AnalyticsEngineDataset;
		INTERNAL_API_SECRET_PROD: SecretsStoreSecret;
		OPENROUTER_API_KEY: SecretsStoreSecret;
	}
}
interface Env extends Cloudflare.Env {}
