/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: f29243a4068b47ee493d040eb277fbac)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env {
		AUTO_ROUTING_CONFIG: KVNamespace;
		INTERNAL_API_SECRET_PROD: SecretsStoreSecret;
		OPENROUTER_API_KEY: SecretsStoreSecret;
	}
}
interface Env extends Cloudflare.Env {}
