/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: e3e13ca2c311b25e145d15e631d407e5)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env {
		INTERNAL_API_SECRET_PROD: SecretsStoreSecret;
		OPENROUTER_API_KEY: SecretsStoreSecret;
	}
}
interface Env extends Cloudflare.Env {}
