export const CONTROL_PLANE_SANDBOX_PERMISSION = {
  external_directory: 'allow',
  read: 'allow',
  edit: 'allow',
  glob: 'allow',
  grep: 'allow',
  list: 'allow',
  bash: 'allow',
  task: 'allow',
  webfetch: 'allow',
  websearch: 'allow',
  codesearch: 'allow',
  lsp: 'allow',
  skill: 'allow',
  todowrite: 'allow',
  todoread: 'allow',
  doom_loop: 'allow',
  suggest: 'deny',
} as const;
