import { timingSafeEqual } from '@kilocode/encryption';
import { microdollar_usage } from '@kilocode/db/schema';
import { eq } from 'drizzle-orm';
import { NextResponse } from 'next/server';
import type { NextRequest } from 'next/server';

import { INTERNAL_API_SECRET } from '@/lib/config.server';
import { db } from '@/lib/drizzle';
import { saveUsageRelatedDataLocally } from '@/lib/ai-gateway/processUsage';
import {
  UsageRecordRequestSchema,
  type UsageRecordResponse,
} from '@/lib/ai-gateway/usage-record-contract';

/**
 * Frankfurt-local sink for AI-gateway usage writes.
 *
 * Callers are SFO instances of `kilocode-global-app`, which are a transatlantic
 * round trip away from the PostgreSQL primary. Executing the write here collapses
 * the row-lock hold on `kilocode_users` / `organizations` /
 * `organization_user_usage` from hundreds of milliseconds to single-digit
 * milliseconds. See `usage-record-client.ts` for the calling side.
 *
 * This route only does the right thing on a deployment whose functions run in
 * Frankfurt. `APP_URL` points at `kilocode-app`, which is Frankfurt-only, and
 * whose rewrites do not divert `/api/internal/*`.
 */

// The usage transaction can legitimately block on a contended counter row up to
// the database `statement_timeout` ceiling of 120s. Allow more than that so a
// slow write is reported rather than silently truncated into a lost billing row.
export const maxDuration = 150;

export async function POST(request: NextRequest): Promise<NextResponse> {
  const secret = request.headers.get('x-internal-api-key');
  if (!INTERNAL_API_SECRET || !secret || !timingSafeEqual(secret, INTERNAL_API_SECRET)) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  const rawBody: unknown = await request.json().catch(() => null);
  const parsed = UsageRecordRequestSchema.safeParse(rawBody);
  if (!parsed.success) {
    // Deliberately a 400: the client must not retry a payload we cannot accept,
    // and a schema failure here means a lost billing row that needs a human.
    console.error('usage record request failed validation', {
      issues: parsed.error.issues.map(issue => ({ path: issue.path.join('.'), code: issue.code })),
    });
    return NextResponse.json({ error: 'Invalid body' }, { status: 400 });
  }

  const { core, metadata, prior_microdollar_usage, posthog_distinct_id } = parsed.data;

  // Idempotency. `core.id` is generated by the sender (`randomUUID()` in
  // `toInsertableDbUsageRecord`) and is the `microdollar_usage` primary key, so a
  // redelivery of a call that already committed is detectable. Without this, a
  // caller-side retry after a lost response would collide on the primary key,
  // burn the retry budget in `insertUsageRecord`, and report the request as
  // unbilled even though it was billed.
  const existing = await db
    .select({ id: microdollar_usage.id })
    .from(microdollar_usage)
    .where(eq(microdollar_usage.id, core.id))
    .limit(1);

  if (existing.length > 0) {
    // Post-commit side effects ran on the first delivery, so do not re-run them.
    // `newMicrodollarsUsed` is not reconstructable here and is only used for
    // PostHog attribution, which already fired.
    const duplicate: UsageRecordResponse = {
      status: 'duplicate',
      result: { usageId: core.id, createdAt: core.created_at, newMicrodollarsUsed: null },
    };
    return NextResponse.json(duplicate);
  }

  const result = await saveUsageRelatedDataLocally(
    core,
    metadata,
    prior_microdollar_usage,
    posthog_distinct_id
  );

  // `saveUsageRelatedDataLocally` swallows database errors and returns null,
  // matching the pre-existing local behaviour. Report it as a successful HTTP
  // exchange with a negative outcome so the client does not retry a write that
  // deliberately gave up.
  const response: UsageRecordResponse = result
    ? { status: 'recorded', result }
    : { status: 'not_recorded', result: null };

  return NextResponse.json(response);
}
