/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 2d304acb2d9aed6310945f563631bfe0)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env {
		INTERNAL_API_SECRET_PROD: SecretsStoreSecret;
	}
}
interface Env extends Cloudflare.Env {}
