/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 3c5604156d25204a17d1431691995d38)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface DevEnv {
		BACKEND_AUTH_TOKEN: string;
	}
	interface Env {
		BACKEND_AUTH_TOKEN: string;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "BACKEND_AUTH_TOKEN">> {}
}
