/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 04ade2a468f996814a98b28a79452ed9)
interface __BaseEnv_Env {
	EXPORT_BUCKET: R2Bucket;
	PRIMARY_STATE_DB: Hyperdrive;
	EXPORT_REPLICA_DB: Hyperdrive;
	EXPORT_QUEUE: Queue;
	INTERNAL_API_SECRET: "local-test-only-not-a-secret";
	R2_ACCESS_KEY_ID: "local-test-access-key";
	R2_SECRET_ACCESS_KEY: "local-test-secret-key";
	R2_ACCOUNT_ID: "local-account";
	R2_BUCKET_NAME: "user-data-export-local";
	USER_DATA_EXPORT_WEB_URL: "http://127.0.0.1:3000";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "INTERNAL_API_SECRET" | "R2_ACCESS_KEY_ID" | "R2_SECRET_ACCESS_KEY" | "R2_ACCOUNT_ID" | "R2_BUCKET_NAME" | "USER_DATA_EXPORT_WEB_URL">> {}
}
