/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: b3b5ebf1648f66c9a3666ddfb13ebe6d)
interface __BaseEnv_Env {
	EXPORT_BUCKET: R2Bucket;
	PRIMARY_STATE_DB: Hyperdrive;
	EXPORT_REPLICA_DB: Hyperdrive;
	EXPORT_WAREHOUSE_DB: Hyperdrive;
	EXPORT_QUEUE: Queue;
	R2_ACCOUNT_ID: "e115e769bcdd4c3d66af59d3332cb394";
	R2_BUCKET_NAME: "user-data-export";
	USER_DATA_EXPORT_WEB_URL: "https://api.kilo.ai";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "R2_ACCOUNT_ID" | "R2_BUCKET_NAME" | "USER_DATA_EXPORT_WEB_URL">> {}
}
