export type ProviderId =
  | 'openrouter'
  | 'gigapotato'
  | 'corethink'
  | 'inception'
  | 'martian'
  | 'minimax'
  | 'mistral'
  | 'novita'
  | 'genlabs'
  | 'streamlake'
  | 'x-ai'
  | 'vercel'
  | 'anthropic'
  | 'custom'
  | 'dev-tools';
