/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 992b95fc6daeb7be8fb41f2c4f2f21fc)
interface __BaseEnv_Env {
	HYPERDRIVE: Hyperdrive;
	FAILOVER_BUFFER: DurableObjectNamespace<import("./src/index").FailoverBufferDO>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "FailoverBufferDO";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
declare module "*.sql" {
	const value: string;
	export default value;
}