/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 0bf3b802e670c028e904286d36bcf118)
interface __BaseEnv_Env {
	HYPERDRIVE: Hyperdrive;
	CONTAINER_BILLING_SERVICES: "";
	CONTAINER_BILLING_USER_IDS: "";
	CONTAINER_BILLING_ORG_IDS: "";
	CONTAINER_BILLING_WARN_REMAINING_MICRODOLLARS: "10000000";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "CONTAINER_BILLING_SERVICES" | "CONTAINER_BILLING_USER_IDS" | "CONTAINER_BILLING_ORG_IDS" | "CONTAINER_BILLING_WARN_REMAINING_MICRODOLLARS">> {}
}
