/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: afc8d75c387b8fd71a14048e2e4e9612)
interface __BaseEnv_Env {
	HYPERDRIVE: Hyperdrive;
	CONTAINER_BILLING_SERVICES: "gastown,cloud-agent-next";
	CONTAINER_BILLING_USER_IDS: "daef8451-f3f3-490e-93f1-21fafc2b005e";
	CONTAINER_BILLING_ORG_IDS: "";
	CONTAINER_BILLING_CLOUD_AGENT_USER_IDS: "f1a848ca-bade-48d8-a5ad-1042d08651e6";
	CONTAINER_BILLING_CLOUD_AGENT_ORG_IDS: "";
	CONTAINER_BILLING_WARN_REMAINING_MICRODOLLARS: "10000000";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "CONTAINER_BILLING_SERVICES" | "CONTAINER_BILLING_USER_IDS" | "CONTAINER_BILLING_ORG_IDS" | "CONTAINER_BILLING_CLOUD_AGENT_USER_IDS" | "CONTAINER_BILLING_CLOUD_AGENT_ORG_IDS" | "CONTAINER_BILLING_WARN_REMAINING_MICRODOLLARS">> {}
}
